
from sqlalchemy import select
from core.database import get_async_session

from models.trainings import Tags
from repositories.tags_repository import TagsRepository

INITIAL_TAGS = [
    {"value": 1, "label": "excel"},
    {"value": 2, "label": "word"},
    {"value": 3, "label": "powerpoint"},
    {"value": 4, "label": "photoshop"},
    {"value": 5, "label": "illustrator"},
    {"value": 6, "label": "premiere pro"},
    {"value": 7, "label": "after effects"},
    {"value": 8, "label": "figma"},
    {"value": 9, "label": "sketch"},
    {"value": 10, "label": "adobe xd"},
    {"value": 11, "label": "invision"},
    {"value": 12, "label": "blender"},
    {"value": 13, "label": "maya"},
    {"value": 14, "label": "3ds max"},
    {"value": 15, "label": "zbrush"},
    {"value": 16, "label": "unity"},
    {"value": 17, "label": "unreal engine"},
    {"value": 18, "label": "visual studio"},
    {"value": 19, "label": "vscode"},
    {"value": 20, "label": "pycharm"},
    {"value": 21, "label": "intellij idea"},
    {"value": 22, "label": "eclipse"},
    {"value": 23, "label": "android studio"},
    {"value": 24, "label": "xcode"},
    {"value": 25, "label": "postman"},
    {"value": 26, "label": "jira"},
    {"value": 27, "label": "confluence"},
    {"value": 28, "label": "trello"},
    {"value": 29, "label": "notion"},
    {"value": 30, "label": "slack"},
    {"value": 31, "label": "teams"},
    {"value": 32, "label": "zoom"},
    {"value": 33, "label": "google meet"},
    {"value": 34, "label": "google docs"},
    {"value": 35, "label": "google sheets"},
    {"value": 36, "label": "google slides"},
    {"value": 37, "label": "tableau"},
    {"value": 38, "label": "power bi"},
    {"value": 39, "label": "looker"},
    {"value": 40, "label": "qlik sense"},
    {"value": 41, "label": "salesforce"},
    {"value": 42, "label": "hubspot"},
    {"value": 43, "label": "mailchimp"},
    {"value": 44, "label": "wordpress"},
    {"value": 45, "label": "elementor"},
    {"value": 46, "label": "shopify"},
    {"value": 47, "label": "woocommerce"},
    {"value": 48, "label": "magento"},
    {"value": 49, "label": "github"},
    {"value": 50, "label": "gitlab"},
    {"value": 51, "label": "bitbucket"},
    {"value": 52, "label": "docker"},
    {"value": 53, "label": "kubernetes"},
    {"value": 54, "label": "aws"},
    {"value": 55, "label": "azure"},
    {"value": 56, "label": "gcp"},
    {"value": 57, "label": "firebase"},
    {"value": 58, "label": "mongodb"},
    {"value": 59, "label": "mysql"},
    {"value": 60, "label": "postgresql"},
    {"value": 61, "label": "oracle"},
    {"value": 62, "label": "sql server"},
    {"value": 63, "label": "redis"},
    {"value": 64, "label": "elasticsearch"},
    {"value": 65, "label": "kibana"},
    {"value": 66, "label": "logstash"},
    {"value": 67, "label": "splunk"},
    {"value": 68, "label": "ansible"},
    {"value": 69, "label": "terraform"},
    {"value": 70, "label": "jenkins"},
    {"value": 71, "label": "circleci"},
    {"value": 72, "label": "gitlab ci"},
    {"value": 73, "label": "travis ci"},
    {"value": 74, "label": "figjam"},
    {"value": 75, "label": "miro"},
    {"value": 76, "label": "mural"},
    {"value": 77, "label": "lucidchart"},
    {"value": 78, "label": "draw.io"},
    {"value": 79, "label": "canva"},
    {"value": 80, "label": "adobe spark"},
    {"value": 81, "label": "final cut pro"},
    {"value": 82, "label": "davinci resolve"},
    {"value": 83, "label": "logic pro"},
    {"value": 84, "label": "ableton live"},
    {"value": 85, "label": "fl studio"},
    {"value": 86, "label": "pro tools"},
    {"value": 87, "label": "audacity"},
    {"value": 88, "label": "obs studio"},
    {"value": 89, "label": "streamlabs"},
    {"value": 90, "label": "node.js"},
    {"value": 91, "label": "python"},
    {"value": 92, "label": "java"},
    {"value": 93, "label": "javascript"},
    {"value": 94, "label": "typescript"},
    {"value": 95, "label": "c#"},
    {"value": 96, "label": "c++"},
    {"value": 97, "label": "go"},
    {"value": 98, "label": "rust"},
    {"value": 99, "label": "kotlin"},
    {"value": 100, "label": "swift"},
    {"value": 101, "label": "react"},
    {"value": 102, "label": "vue.js"},
    {"value": 103, "label": "angular"},
    {"value": 104, "label": "svelte"},
    {"value": 105, "label": "next.js"},
    {"value": 106, "label": "nuxt.js"},
    {"value": 107, "label": "express.js"},
    {"value": 108, "label": "django"},
    {"value": 109, "label": "flask"},
    {"value": 110, "label": "laravel"},
    {"value": 111, "label": "spring boot"},
    {"value": 112, "label": "ruby on rails"},
    {"value": 113, "label": "graphql"},
    {"value": 114, "label": "rest api"},
    {"value": 115, "label": "webpack"},
    {"value": 116, "label": "babel"},
    {"value": 117, "label": "npm"},
    {"value": 118, "label": "yarn"},
    {"value": 119, "label": "pip"},
    {"value": 120, "label": "maven"},
    {"value": 121, "label": "gradle"},
    {"value": 122, "label": "android"},
    {"value": 123, "label": "ios"},
    {"value": 124, "label": "react native"},
    {"value": 125, "label": "flutter"},
    {"value": 126, "label": "xamarin"},
    {"value": 127, "label": "ionic"},
    {"value": 128, "label": "electron"},
    {"value": 129, "label": "tensorflow"},
    {"value": 130, "label": "pytorch"},
    {"value": 131, "label": "keras"},
    {"value": 132, "label": "scikit-learn"},
    {"value": 133, "label": "pandas"},
    {"value": 134, "label": "numpy"},
    {"value": 135, "label": "matplotlib"},
    {"value": 136, "label": "seaborn"},
    {"value": 137, "label": "jupyter"},
    {"value": 138, "label": "colab"},
    {"value": 139, "label": "rstudio"},
    {"value": 140, "label": "spss"},
    {"value": 141, "label": "sas"},
    {"value": 142, "label": "stata"},
    {"value": 143, "label": "matlab"},
    {"value": 144, "label": "autocad"},
    {"value": 145, "label": "solidworks"},
    {"value": 146, "label": "catia"},
    {"value": 147, "label": "revit"},
    {"value": 148, "label": "sketchup"},
    {"value": 149, "label": "rhino"},
    {"value": 150, "label": "fusion 360"},
    {"value": 151, "label": "inventor"},
    {"value": 152, "label": "creo"},
    {"value": 153, "label": "nx"},
    {"value": 154, "label": "solidedge"},
    {"value": 155, "label": "vectary"},
    {"value": 156, "label": "keyshot"},
    {"value": 157, "label": "vray"},
    {"value": 158, "label": "arnold"},
    {"value": 159, "label": "redshift"},
    {"value": 160, "label": "octane render"},
    {"value": 161, "label": "substance painter"},
    {"value": 162, "label": "substance designer"},
    {"value": 163, "label": "marvelous designer"},
    {"value": 164, "label": "houdini"},
    {"value": 165, "label": "nuke"},
    {"value": 166, "label": "fusion"},
    {"value": 167, "label": "hitfilm"},
    {"value": 168, "label": "filmora"},
    {"value": 169, "label": "camtasia"},
    {"value": 170, "label": "screenflow"},
    {"value": 171, "label": "lattice"},
    {"value": 172, "label": "notepad++"},
    {"value": 173, "label": "sublime text"},
    {"value": 174, "label": "atom"},
    {"value": 175, "label": "brackets"},
    {"value": 176, "label": "netbeans"},
    {"value": 177, "label": "phpstorm"},
    {"value": 178, "label": "webstorm"},
    {"value": 179, "label": "rider"},
    {"value": 180, "label": "clion"},
    {"value": 181, "label": "appcode"},
    {"value": 182, "label": "datagrip"},
    {"value": 183, "label": "rublime"},
    {"value": 184, "label": "insomnia"},
    {"value": 185, "label": "swagger"},
    {"value": 186, "label": "apache"},
    {"value": 187, "label": "nginx"},
    {"value": 188, "label": "iis"},
    {"value": 189, "label": "tomcat"},
    {"value": 190, "label": "jetty"},
    {"value": 191, "label": "wildfly"},
    {"value": 192, "label": "glassfish"},
    {"value": 193, "label": "weblogic"},
    {"value": 194, "label": "websphere"},
    {"value": 195, "label": "linux"},
    {"value": 196, "label": "windows"},
    {"value": 197, "label": "macos"},
    {"value": 198, "label": "ubuntu"},
    {"value": 199, "label": "centos"},
    {"value": 200, "label": "debian"}
]


async def create_initial_tags():
    """
    Создаёт начальные типы тегов, если таблица пуста.
    """
    async for session in get_async_session():
        repo = TagsRepository(session)
        count = await repo.count()
        if count == 0:
            try:
                for tags_data in INITIAL_TAGS:
                    action = Tags(**tags_data)
                    session.add(action)
                await session.commit()
                print(f"Успешно создано {len(INITIAL_TAGS)} тегов")
            except Exception as e:
                await session.rollback()
                print(f"❌ Ошибка при создании тегов: {e}")
        else:
            print(f"Теги уже существуют. Всего: {count}")
