"""initial migration3

Revision ID: 26caff175b88
Revises: f866fac345ea
Create Date: 2025-03-10 17:08:53.262990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26caff175b88'
down_revision: Union[str, None] = 'f866fac345ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('events', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('type_events', sa.Column('name_id', sa.Integer(), nullable=False))
    op.drop_constraint('type_events_name_fkey', 'type_events', type_='foreignkey')
    op.create_foreign_key(None, 'type_events', 'name_events', ['name_id'], ['id'])
    op.drop_column('type_events', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_events', sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'type_events', type_='foreignkey')
    op.create_foreign_key('type_events_name_fkey', 'type_events', 'name_events', ['name'], ['id'])
    op.drop_column('type_events', 'name_id')
    op.alter_column('events', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('events', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
