"""dd training_publications table

Revision ID: 3a2f12588b74
Revises: 1fafe71ceeef
Create Date: 2026-02-09 18:18:59.393166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a2f12588b74'
down_revision: Union[str, None] = '1fafe71ceeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_uuid', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(length=100), nullable=False),
    sa.Column('data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('views_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['training_uuid'], ['trainings.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_publications_access_token'), 'training_publications', ['access_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_publications_access_token'), table_name='training_publications')
    op.drop_table('training_publications')
    # ### end Alembic commands ###
