"""add fields tags, time to complete

Revision ID: c3740c99bcd1
Revises: 26f9c6992aa2
Create Date: 2025-10-23 10:50:17.421720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3740c99bcd1'
down_revision: Union[str, None] = '26f9c6992aa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('training_tags',
    sa.Column('training_uuid', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_uuid'], ['trainings.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('training_uuid', 'tag_id')
    )
    op.drop_index('idx_cursants_id_status', table_name='cursants')
    op.drop_table('cursants')
    op.add_column('trainings', sa.Column('level_id', sa.Integer(), nullable=True))
    op.add_column('trainings', sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Ожидаемое время прохождения тренинга в минутах'))
    op.create_foreign_key(None, 'trainings', 'levels', ['level_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_column('trainings', 'duration_minutes')
    op.drop_column('trainings', 'level_id')
    op.create_table('cursants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('currentstatus', sa.CHAR(length=1), server_default=sa.text("'0'::bpchar"), autoincrement=False, nullable=True),
    sa.Column('telegram_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cursants_pkey')
    )
    op.create_index('idx_cursants_id_status', 'cursants', ['id', 'currentstatus'], unique=False)
    op.drop_table('training_tags')
    op.drop_table('tags')
    op.drop_table('levels')
    # ### end Alembic commands ###
